name: CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v3
      with:
         distribution: 'temurin' 
         java-version: '8'

    - name: Build with Maven
      run: |
        mvn clean install
